### ISSUE TITLE
Data format illustration

### ISSUE THREAD

**Issue by momo1986** [haccanri/rec-rl#1]
Hello, I don't know what is the meaning of data-format.
![image](https://user-images.githubusercontent.com/34225874/47279702-512ec400-d605-11e8-85eb-675bbaaf109e.png)
Could you help illustrate it？
For example, what is the meaning of first column, second column and third coulmn.
If you can help, lots of thanks.
Regards!
Neo Yan

**Comment by haccanri** [comment]
The columns are split by ';'，the schema is
```
user_id,
age,
gender,
power (the purchase power),
pageid,
hour,
position,
ctr,
cvr,
price,
isclick,
pay,
matchtype (the type of matching),
terminal,
pvid
```

1. user_id, position, terminal, pvid are not used here
2. age, gender, power are encoded to ids
3. In these columns, position, ctr, cvr, price, isclick, pay are lists which contains information for the items in the same page.

Hopes it can help you!

**Comment by haccanri** [comment]
Hi Neo,

The columns are split by ';'，the schema is

user_id,
age,
gender,
power (the purchase power),
pageid,
hour,
position,
ctr,
cvr,
price,
isclick,
pay,
matchtype (the type of matching),
terminal,
pvid

user_id, position, terminal, pvid are not used here.
age, gender, power are encoded to ids.

In these columns, position, ctr, cvr, price, isclick, pay are lists which
contains information for the items in the same page.

Hopes it can help you！

Best regards
Qing


momo1986 <notifications@github.com> 于2018年10月22日周一 下午2:19写道：
